#!/usr/bin/env python3

import amulet
import requests
import unittest


class TestDeployment(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.deployment = amulet.Deployment(series='trusty')

        mw_config = { 'name': 'MariaDB Test'}
        maria_config = { 'enterprise-eula': True, 'token': 'a202-wg2j'}
        cls.deployment.add('mariadb')
        cls.deployment.add('mediawiki')
        cls.deployment.configure('mediawiki', mw_config)
        cls.deployment.configure('mariadb', maria_config)
        cls.deployment.relate('mediawiki:db', 'mariadb:db')
        cls.deployment.expose('mediawiki')




        try:
            cls.deployment.setup(timeout=1200)
            cls.deployment.sentry.wait()
        except amulet.helpers.TimeoutError:
            amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
        except:
            raise

    '''
    test_relation:  Verify the credentials being sent over the wire were valid
    when attempting to verify the MariaDB Service Status
    '''
    def test_credentials(self):
        dbunit = self.deployment.sentry.unit['mariadb/0']
        db_relation = dbunit.relation('db', 'mediawiki:db')
        db_ip = db_relation['host']
        db_user = db_relation['user']
        db_pass = db_relation['password']
        ctmp = 'mysqladmin status -h {0} -u {1} --password={2}'
        cmd = ctmp.format(db_ip, db_user, db_pass)

        output, code = dbunit.run(cmd)
        if code != 0:
            message = 'Unable to get status of the mariadb serverat %s' % db_ip
            amulet.raise_status(amulet.FAIL, msg=message)

    '''
    test_wiki: Verify Mediawiki setup was successful with MariaDB. No page will
    be available if setup did not complete
    '''
    def test_wiki(self):
        wikiunit = self.deployment.sentry.unit['mediawiki/0']
        wiki_url = "http://{}".format(wikiunit.info['public-address'])
        response = requests.get(wiki_url)
        response.raise_for_status()

if __name__ == '__main__':
    unittest.main()
